config/routes.rb
Rails.application.routes.draw do
	
  resources :blogs, path: '/press'
  devise_for :users
  resources :companies
  root 'home#index'
  get 'sign_in', to: 'home#member'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord

	has_attached_file :logo,
		styles: {
			thumb: '100x100>',
			square: '200x200#',
			medium: '300x300>'
		}

	validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/


	belongs_to :user


	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

	def slug_candidates
      [
        :name,
        [:name, :date_i],
      ]
    end

	def date_i
		self.created_at.to_i
	end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :companies
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :featured, :publish, :user_id)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  def index
    @companies = Company.all
  end


  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_company
      @company = Company.friendly.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:company_number, :name, :bio, :phone_number, :email, :logo, :slug, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def member
  	
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/_form.html.erb
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>

<div class="row">
  <div class="col">
    
    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :body %>
    </div>

  </div>

  <div class="col-md-4">

    <div class="form-inputs">
      <%= f.input :featured %>
      <%= f.input :publish %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>

  </div>

</div>
  
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="blog_box">
  <div class="container">


  </div>
</div>


<div class="container">

<div class="row">
  <div class="col-md-8">
    
    <% @blogs.each do |blog| %>

      <%= blog.title %>
      <%= blog.body %>
      <%= blog.featured %>
      <%= blog.publish %>
      <%= blog.user_id %>
      <%= link_to 'Show', blog %>
      <%= link_to 'Edit', edit_blog_path(blog) %>
      <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

    <%= link_to 'New Blog', new_blog_path %>


  </div>
  <div class="col-md-4">

    <div class="inventory">
      
    </div>

  </div>
</div>




</div>




<style>
  .custom_navbar {
    box-shadow: none !important;
  }
</style>

app/views/blogs/new.html.erb
<div class="container">
	
	<%= render 'form', blog: @blog %>
	<%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @blog.featured %>
</p>

<p>
  <strong>Publish:</strong>
  <%= @blog.publish %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user_id %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.file_field :logo %>


  <div class="field">
    <%= form.label :company_number %>
    <%= form.text_field :company_number, id: :company_company_number, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :company_bio, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :company_phone_number, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :company_email, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="container">
<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Company number</th>
      <th>Name</th>
      <th>Bio</th>
      <th>Phone number</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.company_number %></td>
        <td><%= company.name %></td>
        <td><%= company.bio %></td>
        <td><%= company.phone_number %></td>
        <td><%= company.email %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>
</div>

app/views/companies/new.html.erb
<div class="container">
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>


</div>

app/views/companies/show.html.erb
<div class="cover_space">
  
  <div class="container">

    <div class="row">
      <div class="col-md-2">

          <div class='company_avatar' style=" background-image: url(<%= @company.logo.url(:medium) %>);" > 
          </div>
      
      </div>

      <div class="col-md-9">
        
        <ul class="inf_items">
          <li class="list_item">
            <strong>Company number:</strong> <br>
            <%= @company.company_number %>
          </li> 


          <li class="list_item">
            <strong>Name:</strong> <br>
            <%= @company.name %>
          </li> 
        </ul>

      </div>
    </div>
  
  </div>
  
</div>


<nav class="inpage_navbar">
  <div class="container">
    <ul class="subnav">
      <a href="#"><li class="subnav_items">Why Join Us</li></a>
      <a href="#"><li class="subnav_items">Jobs</li></a>
      <a href="#"><li class="subnav_items">Reviews</li></a>
      <a href="#"><li class="subnav_items">Q&A</li></a>

    </ul>
  </div>
</nav>



<div class="wrapper">

<div class="container">
  
  <div class="row">

    <div class="col-md-3">

      <div class="info_box">

        <ul class="inf_items">
          <li class="list_item">
            <strong>Company number:</strong> <br>
            <%= @company.company_number %>
          </li> 


          <li class="list_item">
            <strong>Name:</strong> <br>
            <%= @company.name %>
          </li> 


          <li class="list_item">
            <strong>Phone number:</strong> <br>
            <%= @company.phone_number %>
          </li> 



          <li class="list_item">
            <strong>Email:</strong> <br>
            <%= @company.email %>
          </li>

        </ul>


        <div class="edit_company_user_only">
          <%= link_to 'Edit', edit_company_path(@company) %> |
          <%= link_to 'Back', companies_path %>
        </div>

      </div>

    </div>  

    <div class="col-md-9 p0">


      <li class="list_item">
        <strong>Bio:</strong> <br>
        <%= @company.bio %>
      </li> 

      
    </div>

  </div>

</div>





</div>

app/views/home/_footer.html.erb
<div class="footer">
  <div class="container">

    <div class="row flat">


    <ul class="col text-align-left">
      <li >© 2015 - 2017 Sebki Ltd.</li>


    </ul>

      <ul class="col text-align-right">
        <li><a href="#">About Us</a></li>
        <li><a href="<%= blogs_path %>">Press</a></li>
        <li><a href="#">Careers</a></li>
        <li><a href="#">Terms of Service</a></li>
        <li><a href="#">Privacy Policy</a></li>
      </ul>

    </div>

  </div>


  <div class="text-alig-center cr-tag">
    Made With <span class="fa fa-heart color-red"></span> In London
  </div>

</div>

app/views/home/_normal.html.erb
<div class="navbar custom_navbar">
  <div class="container-fluid">

    <div class="row">

      <div class="col">
        <div class="branding">
          <a href="<%= root_path%>">Sebki</a>
        </div>

        <ul class="nav_links">
          <li><%= link_to "Jobs", root_path %></li>
          <li><%= link_to "Contractors", root_path %></li>
        </ul>
      </div>

      <div class="col">

        <ul class="nav_links text-right">
          <% if user_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>  
            </li>
          <% end %>

          <% if user_signed_in? %>


          <label class="dropdown">
            <button class="profile_avatar btn btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="">
              <!-- Dropdown button -->
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              
              <a class="dropdown-item" href="<%#= profile_path%>">
                Contractor Profile
              </a>

              <a class="dropdown-item" href="#">
            Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <hr>

              <li cFlass="dropdown-item">
                <%#= link_to'Sign Out', destroy_user_session_path, {:method => :delete}  %>
              </li>
              

            </div>
          </label>

          <% end %>
          <a href="<%= root_path %>">
            <button  class="btn-purple-nav">
              Post a Job
            </button>

          </a>

        </ul>

      </div>

    </div>

  </div>
</div>

app/views/home/_section1.html.erb
<div class="section1" style="background-image: url('assetsandimages/bg.jpg');">

		<div class="container">
			<h3 class="calltoAction">
				<label class="fat_text">Sebki</label> <br>
		        The smart way to hire security guards and officers.
			</h3>

			<div class="search_box">
				<form action="">
					
				<div class="input-group">
				  <input type="text" class="form-control form-control-lg" placeholder="What are you looking for ....">
				  <input type="text" class="form-control form-control-lg" placeholder="Location ....">

				  <div class="input-group-append">
				    <button class="btn btn-purple">Search</button>
				  </div>
				</div>
									
					
					
				</form>
			</div>
		</div>
		
</div>

app/views/home/_section2.html.erb
	<div class="section2">

		<div class="container">

			<div class="row">
				<div class="col">


					<div class="result_items">

						<div class="result_item">
							<h5>Hotel / Residential Security / Concierge - SIA Licenced Officers</h5>

							<h6>Lodge Security Ltd | 5 applicants | <label>Posted 5 munites ago</label> </h6>

							<p>
								Valid Frontline Security Guarding or Door Supervision Licence with experience in a security or retail type role (knowledge of ASCONE is a distinct advantage)....
							</p>

						</div>


						<div class="result_item">
							<h5>Hotel / Residential Security / Concierge - SIA Licenced Officers</h5>

							<h6>Lodge Security Ltd | 5 applicants | <label>Posted 5 munites ago</label> </h6>

							<p>
								Valid Frontline Security Guarding or Door Supervision Licence with experience in a security or retail type role (knowledge of ASCONE is a distinct advantage)....
							</p>

						</div>


					</div>

				</div>
				<div class="col">
					

					<div class="result_items_slim">


						<div class="result_item_slim">
							<div class="row">
								<div class="col-md-3">
									<div class="image_avatar"></div>
								</div>
								<div class="col">
									<h6>LONDON CITY SECURITY</h6>
									<h6>
										5 applications | 
										<label>Joined 5 munites ago</label>
									</h6>		
								</div>
							</div>
						</div>


						<div class="result_item_slim">
							<div class="row">
								<div class="col-md-3">
									<div class="image_avatar"></div>
								</div>
								<div class="col">
									<h6>LONDON CITY SECURITY</h6>
									<h6>
										Lodge Security Ltd | 5 applications | 
										<label>Posted 5 munites ago</label>
									</h6>		
								</div>
							</div>
						</div>

						<div class="result_item_slim">
							<div class="row">
								<div class="col-md-3">
									<div class="image_avatar"></div>
								</div>
								<div class="col">
									<h6>LONDON CITY SECURITY</h6>
									<h6>
										Lodge Security Ltd | 5 applications | 
										<label>Posted 5 munites ago</label>
									</h6>		
								</div>
							</div>
						</div>

						<div class="result_item_slim">
							<div class="row">
								<div class="col-md-3">
									<div class="image_avatar"></div>
								</div>
								<div class="col">
									<h6>LONDON CITY SECURITY</h6>
									<h6>
										Lodge Security Ltd | 5 applications | 
										<label>Posted 5 munites ago</label>
									</h6>		
								</div>
							</div>
						</div>


					</div>

				</div>
			</div>
		</div>
	
</div>

app/views/home/_section3.html.erb
<div class="section3">

	<div class="container">
		
		<div class="row">
			<div class="col s3_items">
				<a href="#">
					<div class="item_avatar" style="background-image: url('https://images.pexels.com/photos/6224/hands-people-woman-working.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
					</div>
					<div class="info">
						<h6>Enhance Your Profile</h6>
						<p>
							With a unique network of clientele be sure you will be exposed to many of the countries most exciting events and unique opportunities.
						</p>
					</div>
				</a>
			</div>

			<div class="col s3_items">
				<a href="#">
					<div class="item_avatar" style="background-image: url('https://images.pexels.com/photos/280377/pexels-photo-280377.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');"></div>
					<div class="info">
						<h6>Last Minute Cover</h6>
						<p>
							With a unique pool of operatives all over the UK, we hold the perfect platform to assist you when time is running out...
						</p>
					</div>
				</a>
			</div>

			<div class="col s3_items">
				<a href="#">
					<div class="item_avatar" style="background-image: url('https://images.pexels.com/photos/194094/pexels-photo-194094.jpeg?auto=compress&cs=tinysrgb&h=650&w=940');"></div>
					<div class="info">
						<h6>Someone Specific?</h6>
						<p>
							For tasks that require experience and specialist skills, our platform filters down operatives and lets you..
						</p>
					</div>
				</a>
			</div>
			
		</div>

	</div>

</div>

app/views/home/_signed_in.html.erb
_normal.html.erb

app/views/home/index.html.erb
<div class="home_page">

	<%= render 'home/section1' %>
	<%= render 'home/section2' %>
	<%= render 'home/section3' %>

</div>


</div>

app/views/home/member.html.erb
<div class="sign_in">
	
	<div class="row">

		<div class="col register" style="background-image: url('https://images.pexels.com/photos/34729/pexels-photo.jpg?cs=srgb&dl=bus-cars-crosswalk-34729.jpg&fm=jpg')">
			<div class="container">
				
			</div>
		</div>

		<div class="col login">
			<div class="container">

				<div class="form_box">
					
					<div class="brand"> Sebki</div>

					<%= simple_form_for(new_user_session_path) do |f| %>
						<div class="form-inputs">
							<%#= f.input :email, required: false, autofocus: true %>
							<%#= f.input :password, required: false %>
							<%#= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
								
							</div>

						<div class="form-group">
							<!-- <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email"> -->
							<%= f.input :email, required: false, autofocus: true, class: 'form-control', id: :InputEmail1 %>

							<small id="emailHelp" class="form-text text-muted">
								We'll never share your email with anyone else.
							</small>

						</div>

						<div class="form-group">
							<label for="exampleInputPassword1">Password</label>
							<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
						</div>
						
						<div class="form-group form-check">
							<input type="checkbox" class="form-check-input" id="exampleCheck1">
						    <label class="form-check-label" for="exampleCheck1">Check me out</label>
						</div>

						<div class="row">
							<div class="col">
								<p>Forgot Password</p>
							</div>
							<div class="col txt-right">
								<button class="btn btn-purple btn-lg">Sign In</button>
							</div>
						</div>

					<% end %>

				</div>

			</div>
		</div>

	</div>
</div>


<style>
	.custom_navbar {
		display: none
	}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sebki</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<%= render 'home/normal' %>
    <div class="page"><%= yield %></div>

    <p class="notice"><%= notice %></p>

    <% if alert %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <%= render 'home/footer' %>

    
  </body>
</html>